### ISSUE TITLE
PHP 8 issue

### ISSUE THREAD

**Issue by jjjj12212** [jtylek/EpesiCRM#11]
Is PHP 8 supported?

I tried the 1.9.0 RC branch and I get the following error:

Error Message: Call to undefined function each() File: /html/crm/test/libs/adodb/adodb.inc.php Line=1137 error backtrace: File: /html/crm/test/libs/adodb/adodb.inc.php line 1601 function called: Execute("", Array (Array (#0))) File: /html/crm/test/include/database.php line 213 function called: GetAssoc("SELECT name,value FROM variables", Array ()) File: /html/crm/test/include/database.php line 504 function called: call_with_retry("GetAssoc", Array ("SELECT name,value FROM variables", Array (#0))) File: /html/crm/test/include/variables.php line 18 function called: GetAssoc("SELECT name,value FROM variables") File: /html/crm/test/include/variables.php line 23 function called: load() File: /html/crm/test/include/version.php line 9 function called: get("version") File: /html/crm/test/index.php line 36 function called: epesi_requires_update() 

Note that I replaced a previous version of EPESI as I was trying to upgrade it.

Thanks,

jjjj12212

**Comment by jtylek** [comment]
The latest version is compatible with PHP 7.3 and you can get it from:
[https://epesi.cloud/knowledgebase/16/Epesi-1.8.2--PHP-7.3.x-fix.html](https://epesi.cloud/knowledgebase/16/Epesi-1.8.2--PHP-7.3.x-fix.html)

Currently branches on Github are not stable - please use the link above to download the Epesi package compatible with PHP up to 7.3.
Compatibility with PHP 7.4 and 8.x will be addressed in the new release but I don't have ETA yet.

**Comment by jjjj12212** [comment]
hi jtylek,
Reverted back to 7.3 and it worked like a charm.

**Comment by jtylek** [comment]
I am glad it worked for you. Thank you for the update.
