### ISSUE TITLE
Can't run application after setup

### ISSUE THREAD

**Issue by jjjj12212** [jtylek/EpesiCRM#8]
**Describe the bug**
on a fresh EPESI CRM, After creating the first CRM user (admin account).
on the screen shows "alert('Invalid request')".
This happens on epesiurl/process.php

![2020-11-02_14-09-29](https://user-images.githubusercontent.com/5553022/97924803-17751580-1d15-11eb-8554-e09d53d3b689.png)

![2020-11-02_11-28-57](https://user-images.githubusercontent.com/5553022/97923759-64f08300-1d13-11eb-9957-aa817cdfd21d.png)

(php 7.3.10, apache 2.4.41)

**To Reproduce**
1. Go to 'epesiurl/setup.php'
2. Select English
3. accept License Agreement
4. Hit ok on the default EPESI root .htaccess
5. enter Database information (create database = yes with full access database user)
6. Everything is green on the next page, hit "Continue with installation"
7.Enter user login and password and hit next

**Expected behavior**
EPESI splash screen to enter login information

**Additional context**
database looks empty. only 11 tables got created. May be normal at this point of the setup though.

**Comment by jtylek** [comment]
See if this version helps:

**Beta version of Epesi 1.8.2 fix addressing PHP 7.3.x compatibility issues:** 
http://releases.epe.si/epesi18x/epesi182PHP73fix.zip 

https://epesi.cloud/knowledgebase/16/Epesi-1.8.2--PHP-7.3.x-fix.html

Please test and report your findings.
Make sure that you paste few lines from php error log.

**Comment by jjjj12212** [comment]
Hi jtylek,

With the 1.8.2, I was able to get past this issue. Is there any particular feature / concerns I should be aware of in this beta version?

Thanks,

**Comment by jtylek** [comment]
Hi @jjjj12212 ,
I am glad it worked for you.
No, you should not be concerned as it is used in production. I consider it a beta release as it was not tested well enough.

Thank you for reporting your findings. 👍
